apiVersion: v1
kind: PersistentVolume
metadata:
  name: datadir-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/datadir/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
